# dataset
dataset: ReDial
tokenize:
  rec: bert
  conv: nltk
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 100
scale: 1
# model
# rec
rec_model: InspiredRec
# conv
conv_model: InspiredConv
# embedding: word2vec
embedding_dim: 128
use_dropout: True
dropout: 0.35
decoder_hidden_size: 128
decoder_num_layers: 1
# optim
rec:
  epoch: 1
  batch_size: 8
  optimizer:
    name: AdamW
    lr: !!float 5e-5
    weight_decay: !!float 0.0000
  early_stop: true
  stop_mode: max
  impatience: 3
  lr_bert: !!float 1e-5
conv:
  epoch: 1
  batch_size: 4
  optimizer:
    name: AdamW
    lr: !!float 1e-4
    eps: !!float 2e-05
    weight_decay: !!float 0.01
  lr_scheduler:
    name: TransformersLinearLR
    warmup_steps: 100
  early_stop: true
  impatience: 3
  stop_mode: min