# dataset
dataset: Inspired
tokenize:
  rec: nltk
  conv: nltk
# dataloader
utterance_truncate: 70
conversation_truncate: 35
scale: 1
# model
# rec
rec_model: ReDialRec
autorec_layer_sizes: [ 1000 ]
autorec_f: sigmoid
autorec_g: sigmoid
# conv
conv_model: ReDialConv
# embedding: word2vec
embedding_dim: 256
utterance_encoder_hidden_size: 256
dialog_encoder_hidden_size: 256
dialog_encoder_num_layers: 1
use_dropout: True
dropout: 0.25
decoder_hidden_size: 256
decoder_num_layers: 1
# optim
rec:
  epoch: 50
  batch_size: 256
  optimizer:
    name: Adam
    lr: !!float 5e-4
  early_stop: true
  impatience: 3
  stop_mode: min
conv:
  epoch: 50
  batch_size: 64
  optimizer:
    name: Adam
    lr: !!float 5e-4
  early_stop: true
  impatience: 3
  stop_mode: min
